image: python:3

stages:
  - test
  - pack
  - push

test:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script: python test/tests.py

pack:
  stage: pack
  script: python setup.py sdist bdist_wheel
  only:
    changes:
      - bfa/*
  artifacts:
    paths:
      - dist/*.gz
      - dist/*.whl

push:
  stage: push
  before_script:
    - pip install twine
  script: twine upload dist/*
  only:
    changes:
      - bfa/*
