image: python:3

stages:
  - test
  - pack
  - push

test:
  stage: test
  before_script:
    - pip install -r requirements.txt
    - pip install coverage
  script:
    - coverage run --source bfa/ -m unittest discover -s test/
    - coverage report -m

pack:
  stage: pack
  script: python setup.py sdist bdist_wheel
  only:
    changes:
      - bfa/*
  artifacts:
    paths:
      - dist/

push:
  stage: push
  before_script:
    - pip install twine
  script: twine upload dist/*
  only:
    changes:
      - bfa/*
